### ISSUE TITLE
Parallel processing

### ISSUE THREAD

**Issue by AyushSemwal** [andreaskapou/Melissa#8]
Hello,

I've been having some issues running create_melissa_obj with no_cores parameter. With no_cores greater than 1 it just displays "Reading file annotation_file.bed" and takes forever to run anything. It doesn't display anything after that. Finally, my Rstudio on workstation hangs and I have to restart it. Can you help me out with this issue?

Thanks
Ayush

**Comment by andreaskapou** [comment]
Hi Ayush,

I haven't seen this issue, and the code essentially just calls the `parallel::mclapply` instead of the `lapply` function. If your dataset isn't that big, could you run the non-parallel version?

PS. In case you have a Mac, I know there is an issue parallel processing (https://github.com/rstudio/rstudio/issues/6692), maybe you could check if you have a general issue with parallel processing with R?

Best,
Andreas
